Add type hints to some of the source code
MetOffice/fab pull request #235
Opened 2023-03-02 04:59 UTC by andy-a-d-nguyen

I added type hints to some of the source code as best as I could. I also followed recommendation from https://mypy.readthedocs.io/en/stable/type_narrowing.html to narrow down variables which are Optional types.

2023-03-02 08:00 UTC, bblay requested changes

2023-03-02 14:18 UTC, andy-a-d-nguyen commented on source/fab/steps/compile_fortran.py
> +    if fpp_flags and '-P' not in fpp_flags:
@bblay I reverted the if condition and used an assertion before the if condition like you suggested.

2023-03-02 14:18 UTC, andy-a-d-nguyen commented on source/fab/steps/compile_fortran.py
> +        self._stage: int | None = None
@bblay I changed the type hints to be compatible with Python 3.7

2023-03-03 08:57 UTC, bblay commented
This looks good, Andy. Fab runs flake8 and mypy on its PRs. It just needs a little change to give us green ticks.
You can see the command used to run [flake8 here](https://github.com/metomi/fab/blob/master/.github/workflows/build.yml#L41) and [mypy here](https://github.com/metomi/fab/blob/master/.github/workflows/build.yml#L37).

I think case I think we just need to restore the Tuple import, as it's used elsewhere.

2023-03-04 03:55 UTC, andy-a-d-nguyen commented
@bblay I re-added the Tuple import in psyclone.py and ran the flake8 linter on the source/ directory. Running the linter on the whole project seems to lint third-party libraries as well.

2023-03-06 11:11 UTC, wilbertcs approved these changes
Change was added as requested.

2023-03-07 09:44 UTC, bblay approved these changes

2023-03-07 09:47 UTC, merged