Psyclone 3 support clean
MetOffice/fab pull request #363
Opened 2024-11-26 08:39 UTC by hiker

Next step to support the new PSyclone syntax: for transformation, no more `-api nemo`, and the output filename is specified using `-o` (not `-opsy` as previously).

Unfortunately, PSyclone did not update the version number during development, so the only way (till the next release) to distinguish new and old syntax is by trying `-api nemo`, and seeing if it fails :( 

There will be a follow up patch that removes this one PSyclone 3.0 is released.

2024-11-28 06:35 UTC, jasonjunweilyu requested changes
Hi @hiker , thanks for this update to support the latest PSyclone. I found only a small typo. Otherwise I think this is good to go to the `develop` branch.

2024-11-29 06:04 UTC, hiker commented on tests/unit_tests/tools/test_psyclone.py
> +def test_psyclone_process_api_new__psyclone(api):
Thanks, well spotted!

2024-11-29 06:07 UTC, hiker commented
Ready :)

2024-11-29 06:27 UTC, jasonjunweilyu approved these changes
Thanks. Now I think this is ready to be merged into `develop` branch.

2024-12-02 06:24 UTC, merged